version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - checkout
      - run:
          name: Set yarn config
          command: |
            yarn config set @taskrabbit:registry https://npm.pkg.github.com
            yarn config set //npm.pkg.github.com/:_authToken ${GITHUB_TOKEN}
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
